#21 Add environment type and fix Config::onProduction
platformsh/config-reader-php pull request #22
Opened 2022-01-12 14:24 UTC by andrewbelcher

2022-02-01 21:59 UTC, damz requested changes
Hi Andrew :wave: 

Thanks for opening this. This looks like an decent improvement to me, but see the inline comment about a backwards compatibility issue.

2022-02-01 21:59 UTC, damz commented on src/Config.php
> +        return $this->getValue('ENVIRONMENT_TYPE') == 'production';
It looks like some legacy environments will not have that variable, so we need to keep the current logic as backwards compatibility here.

2023-07-12 11:42 UTC, flovntp approved these changes

2024-09-18 12:24 UTC, arnested commented
Friendly ping.

I really wanted to use `onProduction()` today, but #21 is still an issue.

My best workaround is just doing `getenv('PLATFORM_ENVIRONMENT_TYPE') === 'production'` instead.

2025-02-12 09:44 UTC, matthiaz commented
Cross posting that this PR did not address the backwards compatibility issue, but this PR does
https://github.com/platformsh/config-reader-php/pull/31

2025-02-25 17:20 UTC, fabpot commented
Closing in favor of #31

2025-02-25 17:20 UTC, closed without merging